// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.dataanalysis.domain.lq;

import java.io.Serializable;

privileged aspect TechnicCountJclPK_Roo_Serializable {
    
    declare parents: TechnicCountJclPK implements Serializable;
    
}
