// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.dataanalysis.domain.jcl;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TeamJcl_Roo_Configurable {
    
    declare @type: TeamJcl: @Configurable;
    
}
